language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install freeglut3-dev libglfw-dev libxml2-dev zlib1g-dev
# sudo: false
#addons:
#  apt:
#    packages:
#    - freeglut3-dev
#    - libglfw-dev # not approved, no container-based build possible
#    - libxml2-dev
#    - zlib1g-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
