language: cpp
compiler:
  - clang
  - gcc
dist: xenial
sudo: false
addons:
  apt:
    packages:
    - cmake
    - freeglut3-dev
    - libarchive-dev
    - libglfw-dev
    - libxml2-dev
    - libzip-dev
    - zlib1g-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
